FORMAT: 1A
HOST: https://api.lobsterchat.com/

# Lobster Chat API

This API provides access to the Lobster Chat messaging service.

# Group Lobsters

This group consists of two resources: /lobsters/ and /lobsters/{id}/.

## Lobsters [/lobsters/]

This resource is for creating and listing lobsters.

### Create Lobster [POST]

Creates a new lobster.

+ Request (application/json)

        {
            "name": "John",
            "claws": 2
        }

+ Response 201 (application/json)

        {
            "id": 1,
            "name": "John",
            "claws": 2
        }

+ Request (application/json)

        {
            "name": "John"
        }

+ Response 400 (application/json)

        {
            "error": "Some parameter is missing."
        }
